#!/bin/bash

exec 2>&1

############# PROJECT SETUP #############################
cp -r {{pkg.path}}/php_files/* {{pkg.svc_data_path}}

chmod +x {{pkg.svc_data_path}}

chown -RL hab:hab {{pkg.svc_data_path}}

############# NGINX SETUP #############################
# Copy the nginx config into position
cp -r {{pkg.svc_config_path}}/nginx.conf \
      {{pkgPathFor "core/nginx"}}/config/nginx.conf

# rename file so we can use fpm default
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

hab svc load core/nginx --group {{svc.group}} --force

echo "PHP listening on 0.0.0.0:{{cfg.http.listen.port}}"
