#!/bin/bash

exec 2>&1

# Copy the nginx config into position
cp -r {{pkg.svc_config_path}}/nginx.conf \
      {{pkgPathFor "core/nginx"}}/config/nginx.conf

cp -r {{pkg.path}}/public_html/* {{pkg.svc_data_path}}
# rename file so we can use fpm default
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

chmod +x {{pkg.svc_data_path}}

chown -RL hab:hab {{pkg.svc_data_path}}

hab svc load core/nginx --group {{svc.group}} --force
